Adds polish to setup.py task runner for tests

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -6,8 +6,51 @@ else
   action="test"
 fi
 
-if [ "$action" = "test" ]; then
-  python -m unittest
-else
-  printf 'Unknown action to run: "%s"\n' "$action" >&2
-fi
+
+install_native_libs() {
+  local required_libs
+  required_libs=<<EOF
+- libtesseract (with source headers)
+- libleptonica (with source headers)
+- gcc
+EOF
+
+  if command -v 'apt-get' 1>/dev/null 2>/dev/null; then
+    install_apt_libs
+  else
+    printf 'Unknown platform. Please setup required libraries manually:\n%s' "$required_libs"
+  fi
+}
+
+sudo_required_to_proceed() {
+  printf 'Root privileges are required in order to install native libs.\n'
+}
+
+install_apt_libs() {
+  local choice
+  while sudo_required_to_proceed && read -p 'Continue (y/n)? ' choice; do
+    case "$choice" in
+      y|Y )
+        sudo apt-get install libtesseract-dev libleptonica-dev build-essential
+        break
+        ;;
+      n|N )
+        printf 'Cancelling...\n'
+        break
+        ;;
+      * )
+        printf 'I didn'"'"'t quite understand that.\n' >&2
+        ;;
+    esac
+  done
+}
+
+case "$action" in
+  setup)
+    install_native_libs
+    ;;
+
+  *)
+    python setup.py "$action"
+    ;;
+esac
